// src/app/Nav.tsx
import Icon from "@/common/Icon";
import { Link } from "react-router-dom";

export default function Nav() {
  return (
    <nav className="flex items-center justify-center h-12 min-h-full text-2xl bg-secondary-100">
      <ul className="flex flex-row flex-nowrap">
        <NavItem text="videos" icon="play" />
        <NavItem text="settings" icon="settings" />

        <li id="status">
          <span className="timeElapsed">{/* {{ timeElapsed }} */}</span>

          {/* <div
          ref="recordingStatus"
          className="circle idle"
          :title="`Start/Stop Recording\n\nWhite => Idle\nRed => Recording`"
          @click="startStopRecording"
        ></div> */}
        </li>
      </ul>
    </nav>
  );
}

/**
 * Text doubles as the link to go to. Add another prop if more specific urls need to be used.
 */
function NavItem(props: { text: string; icon: string }) {
  const { text, icon } = props;

  return (
    <li>
      <Link
        to={`/${text}`}
        className="flex flex-row items-center justify-center px-5 md:px-3 text-white-100 
          fill-current hover:text-white-50 transition-colors ease-in-out duration-250"
      >
        <Icon i={icon} className="mr-1.5" />
        <span className="capitalize hidden md:flex">{text}</span>
      </Link>
    </li>
  );
}

// Casterr/src/components/Nav.vue
<template>
  <nav>
    <ul>
      <li>
        <router-link to="/recordings">
          <Icon i="play" :wh="24" />
          <span>Recordings</span>
        </router-link>
      </li>
      <li>
        <router-link to="/uploads">
          <Icon i="upload" :wh="24" />
          <span>Uploads</span>
        </router-link>
      </li>
      <li>
        <router-link to="/settings">
          <Icon i="settings" :wh="24" />
          <span>Settings</span>
        </router-link>
      </li>
      <li>
        <router-link to="/profile">
          <Icon i="play" :wh="24" />
          <span>Profile</span>
        </router-link>
      </li>
      <li id="status">
        <span id="timeElapsed" class="@RecorderLib.RecordingStatus.ElapsedClass">
          elapsedTime
        </span>

        <!-- Hook this up - add onclick start recording and change class depending on status -->
        <div class="circle safety" title="
          Start/Stop Recording
          White => Idle
          Green => Recording
          Red => Error">
        </div>
      </li>
    </ul>
  </nav>
</template>

<script lang="ts">
import { Component, Vue } from "vue-property-decorator";
import Icon from "./Icon.vue";

@Component({
  components: {
    Icon,
  },
})

export default class Nav extends Vue {}
</script>

<style lang="scss">
nav {
  display: flex;
  min-height: 48px;
  background-color: $secondaryColor;

  ul {
    display: flex;
    align-items: center;
    justify-content: center;
    width: 100%;
    list-style: none;

    li {
      display: inline-block;
      color: $textPrimary;
      font-size: 24px;
      padding: 10px 15px;
      margin: 0 5px;
      cursor: pointer;

      a {
        display: flex;
        align-items: center;
        justify-content: center;
        transition: color 250ms ease;
      }

      svg {
        fill: $textPrimary;
        margin: 0 8px 0 0;
        transition: fill 250ms ease;

        @media (max-width: 910px) {
          transition: width 250ms ease;
          margin: 0;
          width: 80px;
        }

        @media (max-width: 600px) {
          width: 20px;
        }
      }

      span:not(#timeElapsed) {
        @media (max-width: 910px) {
          display: none;
        }
      }

      &:hover {
        a,
        svg {
          color: $textPrimaryHover;
          fill: $textPrimaryHover;
        }
      }

      &#status {
        display: flex;
        align-items: center;
        position: absolute;
        right: 10px;
        cursor: default;

        span {
          opacity: 1;
          margin: 0 15px;
          font-size: 18px;
          transition: opacity 250ms ease-in-out;

          &.hidden {
            display: unset !important;
            opacity: 0 !important;
          }
        }

        .circle {
          width: 20px;
          height: 20px;
          padding: 0 !important;
          border-radius: 50%;
          transition: background-color 250ms ease-in-out,
                      box-shadow       250ms ease-in-out;
          cursor: pointer;

          &.safety {
            background-color: $safetyColor;
            box-shadow: 0 0 8px $safetyColor;
          }

          &.idle {
            background-color: $textPrimary;
            box-shadow: 0 0 8px $textPrimary;
          }

          &.danger {
            background-color: $dangerColor;
            box-shadow: 0 0 8px $dangerColor;
          }
        }
      }
    }
  }
}
</style>
