// src/app/Dragger.tsx
import Icon, { Icons } from "@/common/Icon";
import { ipcRenderer } from "electron";
import React from "react";

export default function Dragger() {
  return (
    <div
      className="flex flex-row-reverse h-4 bg-quaternary-100"
      style={{ WebkitAppRegion: "drag" } as React.CSSProperties}
    >
      <DraggerItem icon="close" />
      <DraggerItem icon="max" />
      <DraggerItem icon="min" />
    </div>
  );
}

function DraggerItem(props: { icon: Icons }) {
  const { icon } = props;

  const manageWindow = () => {
    ipcRenderer.send("manage-window", icon);
  };

  return (
    <div
      onClick={manageWindow}
      className={`flex justify-center items-center h-full w-8 fill-current text-white-100 cursor-pointer ${
        icon === "close" ? "hover:bg-red-100" : "hover:bg-white-50"
      }`}
      style={{ WebkitAppRegion: "no-drag" } as React.CSSProperties}
    >
      <Icon i={icon} wh={12} />
    </div>
  );
}

// src/components/Dragger.vue
<template>
  <div class="dragger">
    <div class="minMaxClose">
      <div class="close" @click="manageWindow('close')">
        <Icon i="close" :wh="12" />
      </div>
      <div class="max" @click="manageWindow('maximize')">
        <Icon i="max" :wh="12" />
      </div>
      <div class="min" @click="manageWindow('minimize')">
        <Icon i="min" :wh="12" />
      </div>
    </div>
  </div>
</template>

<script lang="ts">
import { Vue, Component } from "vue-property-decorator";
import Icon from "./Icon.vue";
import { ipcRenderer } from "electron";

@Component({
  components: {
    Icon
  }
})
export default class Dragger extends Vue {
  public manageWindow(msg: string) {
    ipcRenderer.send("manage-window", msg);
  }
}
</script>

<style lang="scss">
.dragger {
  height: 18px;
  overflow: hidden;
  -webkit-app-region: drag;
  background-color: $darkAccentColor;

  .minMaxClose {
    display: flex;
    flex-direction: row-reverse;
    fill: $textPrimary;

    div {
      position: relative;
      display: flex;
      justify-content: center;
      align-items: center;
      -webkit-app-region: no-drag;
      width: 30px;
      height: 18px;
      cursor: pointer;

      &:hover {
        background-color: $lightHoverColor;
      }
    }

    .close:hover {
      background-color: $dangerColor;
    }
  }
}
</style>
